version: '3.9'
services:
    redis:
      image: redis
      container_name: redis
      ports:
        - 6379:6379
      volumes:
        - ./.volumes/data/redis:/data
        - ./.volumes/config/redis.conf:/redis.conf
      command: redis-server /redis.conf

    k6:
      image: loadimpact/k6
      container_name: k6
      environment:
        - K6_OUT=influxdb=http://influxdb:8086/k6
      volumes:
        - ./.volumes/scripts:/scripts
    
    influxdb:
      image: influxdb:1.8.10
      container_name: influxdb
      environment:
        - INFLUXDB_DB=k6
        - INFLUXDB_HTTP_MAX_BODY_SIZE=0
      ports:
        - 8086:8086
      volumes:
        - ./.volumes/data/influxdb:/var/lib/influxdb

    grafana:
      image: grafana/grafana
      container_name: grafana
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      ports:
        - 3000:3000
      volumes:
        - ./.volumes/data/grafana:/var/lib/grafana